data = [
    {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013691",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13691",
          "subj" : "MAAE",
          "sec" : "B",
          "title" : "Engineering Graphical Design",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Henry Saari",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "13:35 - 14:25",
          "also" : "MAAE 2001 L2 or L3 or L4",
          "info" : "Blended delivery; some lectures will be synchronous and recorded and some lectures will be asynchronous.",
          "code" : "2001"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013692",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13692",
          "subj" : "MAAE",
          "sec" : "C",
          "title" : "Engineering Graphical Design",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Henry Saari",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Wed Fri",
          "time" : "08:35 - 09:25",
          "also" : "MAAE 2001 L2 or L3 or L4",
          "info" : "Blended delivery; some lectures will be synchronous and recorded and some lectures will be asynchronous.",
          "code" : "2001"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013693",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13693",
          "subj" : "MAAE",
          "sec" : "L2",
          "title" : "Engineering Graphical Design",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Henry Saari",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "11:35 - 13:25",
          "also" : "MAAE 2001 B or C",
          "info" : "Blended; assignments will be made available and will  be completed by individual students and groups remotely.  Labs will be used for synchronous activities with TAs  including office hours, assistance with course work, project presentations, and in-class exams.",
          "code" : "2001"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013695",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13695",
          "subj" : "MAAE",
          "sec" : "L4",
          "title" : "Engineering Graphical Design",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Henry Saari",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Wed Fri",
          "time" : "14:35 - 16:25",
          "also" : "MAAE 2001 B or C",
          "info" : "Blended; assignments will be made available and will be  completed by individual students and groups remotely. Labs will be used for synchronous activities with TAs including  office hours, assistance with course work, project presenta tions, and in-class exams.",
          "code" : "2001"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013696",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13696",
          "subj" : "MAAE",
          "sec" : "C",
          "title" : "Engineering Dynamics",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Mojtaba Ahmadi",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "10:05 - 11:25",
          "also" : "MAAE 2101 L1 or L2",
          "info" : "Blended course delivery. Precludes additional credit for CIVE 2101. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here: https://carleton.ca/csas/pass",
          "code" : "2101"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013700",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13700",
          "subj" : "MAAE",
          "sec" : "C",
          "title" : "Mechanics of Solids I",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Jie Liu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "11:35 - 12:55",
          "also" : "MAAE 2202 L1 or L2 or L3 or L4",
          "info" : "Synchronous delivery; participation encouraged. Lectures will be recorded and made available to students. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here: https://carleton.ca/csas/pass Precludes additional credit for CIVE 2200.",
          "code" : "2202"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013701",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13701",
          "subj" : "MAAE",
          "sec" : "L1",
          "title" : "Mechanics of Solids I",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Jie Liu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "14:35 - 17:25",
          "also" : "MAAE 2202 B or C",
          "info" : "Synchronous delivery. participation encouraged and evaluated Lab sessions will not be recorded.",
          "code" : "2202"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013702",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13702",
          "subj" : "MAAE",
          "sec" : "L2",
          "title" : "Mechanics of Solids I",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Jie Liu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 2202 B or C",
          "info" : "Synchronous delivery; participation encouraged and evaluated Lab sessions will not be recorded.",
          "code" : "2202"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013704",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13704",
          "subj" : "MAAE",
          "sec" : "L4",
          "title" : "Mechanics of Solids I",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Jie Liu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Thu",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 2202 B or C",
          "info" : "Synchronous delivery; participation encouraged and evaluated Lab sessions will not be recorded.",
          "code" : "2202"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013705",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13705",
          "subj" : "MAAE",
          "sec" : "D",
          "title" : "Fluid Mechanics I",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Jason Etele",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Wed Fri",
          "time" : "13:05 - 14:25",
          "also" : "MAAE 2300 L1 or L2 or L3 or L4 or L5 or L6 or L7 or L8",
          "info" : "Synchronous course delivery. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here: https://carleton.ca/csas/pass",
          "code" : "2300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013707",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13707",
          "subj" : "MAAE",
          "sec" : "F",
          "title" : "Fluid Mechanics I",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Karen Taylor",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "14:35 - 15:55",
          "also" : "MAAE 2300 L1 or L2 or L3 or L4 or L5 or L6 or L7 or L8",
          "info" : "Mixture of asynchronous and synchronous activities. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here: https://carleton.ca/csas/pass",
          "code" : "2300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013708",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13708",
          "subj" : "MAAE",
          "sec" : "L1",
          "title" : "Fluid Mechanics I",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Jason Etele",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue",
          "time" : "11:35 - 14:25",
          "also" : "MAAE 2300 D or E or F",
          "code" : "2300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013709",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13709",
          "subj" : "MAAE",
          "sec" : "L2",
          "title" : "Fluid Mechanics I",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Jason Etele",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 2300 D or E or F",
          "code" : "2300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013710",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13710",
          "subj" : "MAAE",
          "sec" : "L3",
          "title" : "Fluid Mechanics I",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Jason Etele",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Thu",
          "time" : "14:35 - 17:25",
          "also" : "MAAE 2300 D or E or F",
          "code" : "2300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013711",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13711",
          "subj" : "MAAE",
          "sec" : "L4",
          "title" : "Fluid Mechanics I",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Jason Etele",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 2300 D or E or F",
          "code" : "2300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013713",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13713",
          "subj" : "MAAE",
          "sec" : "L6",
          "title" : "Fluid Mechanics I",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Jason Etele",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Wed",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 2300 D or E or F",
          "code" : "2300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013714",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13714",
          "subj" : "MAAE",
          "sec" : "L7",
          "title" : "Fluid Mechanics I",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Jason Etele",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Thu",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 2300 D or E or F",
          "code" : "2300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013715",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13715",
          "subj" : "MAAE",
          "sec" : "L8",
          "title" : "Fluid Mechanics I",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Jason Etele",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "14:35 - 17:25",
          "also" : "MAAE 2300 D or E or F",
          "code" : "2300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013716",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13716",
          "subj" : "MAAE",
          "sec" : "D",
          "title" : "Thermodynamics & Heat Transfer",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Junjie Gu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Wed Fri",
          "time" : "13:05 - 14:25",
          "also" : "MAAE 2400 L1 or L2 or L3 or L4 or L5 or L6 or L7 or L8",
          "info" : "Mixture of synchronous and asynchronous activities. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here: https://carleton.ca/csas/pass",
          "code" : "2400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013718",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13718",
          "subj" : "MAAE",
          "sec" : "F",
          "title" : "Thermodynamics & Heat Transfer",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Junjie Gu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "16:05 - 17:25",
          "also" : "MAAE 2400 L1 or L2 or L3 or L4 or L5 or L6 or L7 or L8",
          "info" : "Mixture of synchronous and asynchronous activities. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here:  https://carleton.ca/csas/pass",
          "code" : "2400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013719",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13719",
          "subj" : "MAAE",
          "sec" : "L1",
          "title" : "Thermodynamics & Heat Transfer",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Junjie Gu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 2400 D or E or F",
          "info" : "The lab will be delivered online. Details will be posted on cuLearn.",
          "code" : "2400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013720",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13720",
          "subj" : "MAAE",
          "sec" : "L2",
          "title" : "Thermodynamics & Heat Transfer",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Junjie Gu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Thu",
          "time" : "14:35 - 17:25",
          "also" : "MAAE 2400 D or E or F",
          "info" : "The lab will be delivered online. Details will be posted on cuLearn.",
          "code" : "2400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013723",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13723",
          "subj" : "MAAE",
          "sec" : "L5",
          "title" : "Thermodynamics & Heat Transfer",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Junjie Gu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Wed",
          "time" : "14:35 - 17:25",
          "also" : "MAAE 2400 D or E or F",
          "info" : "The lab will be delivered online. Details will be posted on cuLearn.",
          "code" : "2400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013724",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13724",
          "subj" : "MAAE",
          "sec" : "L6",
          "title" : "Thermodynamics & Heat Transfer",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Junjie Gu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Thu",
          "time" : "11:35 - 14:25",
          "also" : "MAAE 2400 D or E or F",
          "info" : "The lab will be delivered online. Details will be posted on cuLearn.",
          "code" : "2400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013725",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13725",
          "subj" : "MAAE",
          "sec" : "L7",
          "title" : "Thermodynamics & Heat Transfer",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "No",
          "prereq" : "No",
          "instruct" : "Junjie Gu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue",
          "time" : "11:35 - 14:25",
          "also" : "MAAE 2400 D or E or F",
          "info" : "The lab will be delivered online. Details will be posted on cuLearn.",
          "code" : "2400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013726",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13726",
          "subj" : "MAAE",
          "sec" : "L8",
          "title" : "Thermodynamics & Heat Transfer",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Junjie Gu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "11:35 - 14:25",
          "also" : "MAAE 2400 D or E or F",
          "info" : "The lab will be delivered online. Details will be posted on cuLearn.",
          "code" : "2400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013727",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13727",
          "subj" : "MAAE",
          "sec" : "C",
          "title" : "Engineering Materials",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Oren Petel",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "08:35 - 09:55",
          "also" : "MAAE 2700 L1 or L2 or L3",
          "info" : "Precludes additional credit for CIVE 2700. This course will include asynchronous lectures available for  viewing on CULearn as well as recorded synchronous activiti es during the allotted class time.",
          "code" : "2700"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013728",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13728",
          "subj" : "MAAE",
          "sec" : "L1",
          "title" : "Engineering Materials",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Oren Petel",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "14:35 - 17:25",
          "also" : "MAAE 2700 C",
          "info" : "The lab will be delivered asynchronously.",
          "code" : "2700"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013729",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13729",
          "subj" : "MAAE",
          "sec" : "L2",
          "title" : "Engineering Materials",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Oren Petel",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 2700 C",
          "info" : "The lab will be delivered asynchronously.",
          "code" : "2700"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013731",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13731",
          "subj" : "MAAE",
          "sec" : "C",
          "title" : "Dynamics of Machinery",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "John Hayes",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "14:35 - 15:55",
          "also" : "MAAE 3004 L1 or L2",
          "info" : "Asynchronous course delivery. Registration time conflicts permitted. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here: https://carleton.ca/csas/pass",
          "code" : "3004"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013733",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13733",
          "subj" : "MAAE",
          "sec" : "L2",
          "title" : "Dynamics of Machinery",
          "cred" : "0",
          "type" : "Tutorial",
          "restrict" : "No",
          "prereq" : "No",
          "instruct" : "John Hayes",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Thu",
          "time" : "08:35 - 10:25",
          "also" : "MAAE 3004 C",
          "info" : "Asynchronous lab delivery. Registration time conflicts permitted.",
          "code" : "3004"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013734",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13734",
          "subj" : "MAAE",
          "sec" : "C",
          "title" : "Mechanics of Solids II",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Rong Liu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "08:35 - 09:55",
          "also" : "MAAE 3202 L1 or L2",
          "info" : "The lectures will be delivered synchronously. They are recorded and will be made available to students. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here: https://carleton.ca/csas/pass Precludes additional credit for CIVE 3202.",
          "code" : "3202"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013735",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13735",
          "subj" : "MAAE",
          "sec" : "L1",
          "title" : "Mechanics of Solids II",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Rong Liu",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 3202 C",
          "info" : "The PA and lab will be run synchronously.",
          "code" : "3202"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013738",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13738",
          "subj" : "MAAE",
          "sec" : "L1",
          "title" : "Fluid Mechanics II",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "John Gaydos",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Wed",
          "time" : "14:35 - 17:25",
          "also" : "MAAE 3300 C",
          "info" : "Lab video recordings will be made available to students according to the course schedule.",
          "code" : "3300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013739",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13739",
          "subj" : "MAAE",
          "sec" : "L2",
          "title" : "Fluid Mechanics II",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "John Gaydos",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue",
          "time" : "14:35 - 17:25",
          "also" : "MAAE 3300 C",
          "info" : "Lab videos will be made available to students according to the course schedule.",
          "code" : "3300"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013741",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13741",
          "subj" : "MAAE",
          "sec" : "A",
          "title" : "Applied Thermodynamics",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Metin Yaras",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "11:35 - 12:55",
          "also" : "MAAE 3400 L1 or L2 or L3 or L4 or L5 or L6",
          "info" : "Synchronous course, meetings via web conferencing at schedul ed time. Homework, assignments and other activities will be completed outside of class. Students must be available at th e scheduled meeting time. Synchronous meetings will not be r ecorded. Blended course delivery. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here:  https://carleton.ca/csas/pass",
          "code" : "3400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013742",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13742",
          "subj" : "MAAE",
          "sec" : "B",
          "title" : "Applied Thermodynamics",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Ian Beausoleil-Morrison",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Wed Fri",
          "time" : "11:35 - 12:55",
          "also" : "MAAE 3400 L1 or L2 or L3 or L4 or L5 or L6",
          "info" : "Some lecture materials will be pre-recorded, but the class w ill meet regularly during the scheduled time to review and e xpand upon the pre-recorded materials and to treat additiona l topics.  The synchronous classes will not be recorded. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here:  https://carleton.ca/csas/pass",
          "code" : "3400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013743",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13743",
          "subj" : "MAAE",
          "sec" : "C",
          "title" : "Applied Thermodynamics",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Metin Yaras",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "13:05 - 14:25",
          "also" : "MAAE 3400 L1 or L2 or L3 or L4 or L5 or L6",
          "info" : "Synchronous course, meetings via web conferencing at schedul ed time. Homework, assignments and other activities will be completed outside of class. Students must be available at th e scheduled meeting time. Synchronous meetings will not be r ecorded. This course will be supported by Peer Assisted Study Sessions (PASS). Further information here:  https://carleton.ca/csas/pass",
          "code" : "3400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013745",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13745",
          "subj" : "MAAE",
          "sec" : "L2",
          "title" : "Applied Thermodynamics",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Metin Yaras",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Thu",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 3400 A or B or C",
          "info" : "Synchronous tutorials via web conferencing at scheduled time . Lab experiments will be based on video recorded lab sessio ns conducted by a teaching assistant. Students must be avail able at the scheduled tutorial time. Synchronous tutorials w ill not be recorded.",
          "code" : "3400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013746",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13746",
          "subj" : "MAAE",
          "sec" : "L3",
          "title" : "Applied Thermodynamics",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Metin Yaras",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "14:35 - 17:25",
          "also" : "MAAE 3400 A or B or C",
          "info" : "Synchronous tutorials via web conferencing at scheduled time . Lab experiments will be based on video recorded lab sessio ns conducted by a teaching assistant. Students must be avail able at the scheduled tutorial time. Synchronous tutorials w ill not be recorded.",
          "code" : "3400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013747",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13747",
          "subj" : "MAAE",
          "sec" : "L4",
          "title" : "Applied Thermodynamics",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Metin Yaras",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 3400 A or B or C",
          "info" : "Synchronous tutorials via web conferencing at scheduled time . Lab experiments will be based on video recorded lab sessio ns conducted by a teaching assistant. Students must be avail able at the scheduled tutorial time. Synchronous tutorials w ill not be recorded.",
          "code" : "3400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013748",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13748",
          "subj" : "MAAE",
          "sec" : "L5",
          "title" : "Applied Thermodynamics",
          "cred" : "0",
          "type" : "Laboratory",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Metin Yaras",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Wed",
          "time" : "08:35 - 11:25",
          "also" : "MAAE 3400 A or B or C",
          "info" : "Synchronous tutorials via web conferencing at scheduled time . Lab experiments will be based on video recorded lab sessio ns conducted by a teaching assistant. Students must be avail able at the scheduled tutorial time. Synchronous tutorials w ill not be recorded.",
          "code" : "3400"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013750",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13750",
          "subj" : "MAAE",
          "sec" : "A",
          "title" : "Feedback Control Systems",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Donald Russell",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "13:05 - 14:25",
          "also" : "MAAE 3500 L1 or L2 or L3",
          "info" : "Asynchronous delivery; scheduled time will be used for offic e hours and tests. Precludes additional credit for MAAE 4500 (no longer offered), SYSC4505",
          "code" : "3500"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013751",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13751",
          "subj" : "MAAE",
          "sec" : "B",
          "title" : "Feedback Control Systems",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Robin Chhabra",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Tue Thu",
          "time" : "11:35 - 12:55",
          "also" : "MAAE 3500 L1 or L2 or L3",
          "info" : "Asynchronous delivery; scheduled time will be used for offic e hours. Precludes additional credit for MAAE 4500 (no longer offered), SYSC 4505.",
          "code" : "3500"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013752",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13752",
          "subj" : "MAAE",
          "sec" : "C",
          "title" : "Feedback Control Systems",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "Yes",
          "instruct" : "Steve Ulrich",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Wed Fri",
          "time" : "11:35 - 12:55",
          "also" : "MAAE 3500 L1 or L2 or L3",
          "info" : "Asynchronous delivery; scheduled time will be used for offic e hours and tests. Precludes additional credit for MAAE 4500 (no longer offered), SYSC 4505.",
          "code" : "3500"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013754",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13754",
          "subj" : "MAAE",
          "sec" : "L2",
          "title" : "Feedback Control Systems",
          "cred" : "0",
          "type" : "Problem Analysis",
          "restrict" : "No",
          "prereq" : "No",
          "instruct" : "Steve Ulrich",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Thu",
          "time" : "14:35 - 15:55",
          "also" : "MAAE 3500 A or B or C",
          "info" : "Registration time conflicts permitted Asynchronous lab delivery.",
          "code" : "3500"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013755",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13755",
          "subj" : "MAAE",
          "sec" : "L3",
          "title" : "Feedback Control Systems",
          "cred" : "0",
          "type" : "Problem Analysis",
          "restrict" : "No",
          "prereq" : "No",
          "instruct" : "Steve Ulrich",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "16:05 - 17:25",
          "also" : "MAAE 3500 A or B or C",
          "info" : "Asynchronous delivery. Registration time conflicts permitted",
          "code" : "3500"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013757",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Full, No Waitlist",
          "crn" : "13757",
          "subj" : "MAAE",
          "sec" : "A",
          "title" : "Nuclear Power Plant Design",
          "cred" : ".5",
          "type" : "Lecture",
          "restrict" : "Yes",
          "prereq" : "No",
          "instruct" : "Sam Gyepi-Garbrah",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Thu",
          "time" : "18:05 - 20:55",
          "info" : "Blended delivery. Be prepared to meet during some of the scheduled timeslots. Specific dates to be communicated directly by the instructor. Synchronous activities will be recorded and made available for students.",
          "code" : "4902"
        }
      },
      {
        "_index" : "classes202110",
        "_type" : "_doc",
        "_id" : "20211013771",
        "_score" : 1.0,
        "_source" : {
          "avail" : "Open",
          "crn" : "13771",
          "subj" : "MAAE",
          "sec" : "T1",
          "title" : "Engineering Design Project",
          "cred" : "0",
          "type" : "Independent Study",
          "restrict" : "No",
          "prereq" : "No",
          "instruct" : "John Gaydos",
          "date" : "Jan 11, 2021 to Apr 14, 2021",
          "days" : "Fri",
          "time" : "13:05 - 14:25",
          "also" : "MAAE 4907 A or B or C or D or E or F or G or H or I or J or M",
          "info" : "Project Seminar Session",
          "code" : "4907"
        }
      }

    ];